# Goal
string arm_names          # "left", "right", "both"
string command            # "open", "grasp", "move"
float64 width             # [m], 0.08 open, 0.0 grasp/close
float64 speed             # [m/s]
float64 force             # [N], used for grasp
float64 epsilon_inner     # [m], used for grasp
float64 epsilon_outer     # [m], used for grasp
bool use_weld             # MuJoCo-only object weld attach/detach
string weld_name          # currently supports "weld_blue_right_tcp"
---
# Result
bool success
string message
---
# Feedback
string status
